// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bgp/v1/bgp.proto

package bgpv1

import (
	v1 "github.com/msaeedb40/straitgateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBGPPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBGPPeersRequest) Reset() {
	*x = ListBGPPeersRequest{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBGPPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBGPPeersRequest) ProtoMessage() {}

func (x *ListBGPPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBGPPeersRequest.ProtoReflect.Descriptor instead.
func (*ListBGPPeersRequest) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{0}
}

type ListBGPPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*BGPPeerInfo         `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBGPPeersResponse) Reset() {
	*x = ListBGPPeersResponse{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBGPPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBGPPeersResponse) ProtoMessage() {}

func (x *ListBGPPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBGPPeersResponse.ProtoReflect.Descriptor instead.
func (*ListBGPPeersResponse) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{1}
}

func (x *ListBGPPeersResponse) GetPeers() []*BGPPeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type BGPPeerInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress        string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	PeerAsn            uint32                 `protobuf:"varint,2,opt,name=peer_asn,json=peerAsn,proto3" json:"peer_asn,omitempty"`
	LocalAsn           uint32                 `protobuf:"varint,3,opt,name=local_asn,json=localAsn,proto3" json:"local_asn,omitempty"`
	SessionState       string                 `protobuf:"bytes,4,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	PrefixesAdvertised uint32                 `protobuf:"varint,5,opt,name=prefixes_advertised,json=prefixesAdvertised,proto3" json:"prefixes_advertised,omitempty"`
	PrefixesReceived   uint32                 `protobuf:"varint,6,opt,name=prefixes_received,json=prefixesReceived,proto3" json:"prefixes_received,omitempty"`
	BfdState           string                 `protobuf:"bytes,7,opt,name=bfd_state,json=bfdState,proto3" json:"bfd_state,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BGPPeerInfo) Reset() {
	*x = BGPPeerInfo{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPPeerInfo) ProtoMessage() {}

func (x *BGPPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPPeerInfo.ProtoReflect.Descriptor instead.
func (*BGPPeerInfo) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{2}
}

func (x *BGPPeerInfo) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *BGPPeerInfo) GetPeerAsn() uint32 {
	if x != nil {
		return x.PeerAsn
	}
	return 0
}

func (x *BGPPeerInfo) GetLocalAsn() uint32 {
	if x != nil {
		return x.LocalAsn
	}
	return 0
}

func (x *BGPPeerInfo) GetSessionState() string {
	if x != nil {
		return x.SessionState
	}
	return ""
}

func (x *BGPPeerInfo) GetPrefixesAdvertised() uint32 {
	if x != nil {
		return x.PrefixesAdvertised
	}
	return 0
}

func (x *BGPPeerInfo) GetPrefixesReceived() uint32 {
	if x != nil {
		return x.PrefixesReceived
	}
	return 0
}

func (x *BGPPeerInfo) GetBfdState() string {
	if x != nil {
		return x.BfdState
	}
	return ""
}

func (x *BGPPeerInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ListBGPPrefixesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress   string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBGPPrefixesRequest) Reset() {
	*x = ListBGPPrefixesRequest{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBGPPrefixesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBGPPrefixesRequest) ProtoMessage() {}

func (x *ListBGPPrefixesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBGPPrefixesRequest.ProtoReflect.Descriptor instead.
func (*ListBGPPrefixesRequest) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{3}
}

func (x *ListBGPPrefixesRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

type ListBGPPrefixesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []*BGPPrefix           `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBGPPrefixesResponse) Reset() {
	*x = ListBGPPrefixesResponse{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBGPPrefixesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBGPPrefixesResponse) ProtoMessage() {}

func (x *ListBGPPrefixesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBGPPrefixesResponse.ProtoReflect.Descriptor instead.
func (*ListBGPPrefixesResponse) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{4}
}

func (x *ListBGPPrefixesResponse) GetPrefixes() []*BGPPrefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type BGPPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *v1.IPPrefix           `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NextHop       string                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	LocalPref     uint32                 `protobuf:"varint,3,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	Med           uint32                 `protobuf:"varint,4,opt,name=med,proto3" json:"med,omitempty"`
	AsPath        []uint32               `protobuf:"varint,5,rep,packed,name=as_path,json=asPath,proto3" json:"as_path,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BGPPrefix) Reset() {
	*x = BGPPrefix{}
	mi := &file_bgp_v1_bgp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BGPPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGPPrefix) ProtoMessage() {}

func (x *BGPPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_bgp_v1_bgp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGPPrefix.ProtoReflect.Descriptor instead.
func (*BGPPrefix) Descriptor() ([]byte, []int) {
	return file_bgp_v1_bgp_proto_rawDescGZIP(), []int{5}
}

func (x *BGPPrefix) GetPrefix() *v1.IPPrefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *BGPPrefix) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *BGPPrefix) GetLocalPref() uint32 {
	if x != nil {
		return x.LocalPref
	}
	return 0
}

func (x *BGPPrefix) GetMed() uint32 {
	if x != nil {
		return x.Med
	}
	return 0
}

func (x *BGPPrefix) GetAsPath() []uint32 {
	if x != nil {
		return x.AsPath
	}
	return nil
}

func (x *BGPPrefix) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_bgp_v1_bgp_proto protoreflect.FileDescriptor

const file_bgp_v1_bgp_proto_rawDesc = "" +
	"
" +
	"bgp/v1/bgp.protostraitgateway.bgp.v1common/v1/common.proto\"
" +
	"ListBGPPeersRequest\"O
" +
	"ListBGPPeersResponse7
" +
	"peers (2!.straitgateway.bgp.v1.BGPPeerInfoRpeers\"¯
" +
	"BGPPeerInfo!
" +
	"peer_address (	RpeerAddress
" +
	"peer_asn (RpeerAsn
" +
	"	local_asn (RlocalAsn#
" +
	"session_state (	RsessionState/
" +
	"prefixes_advertised (RprefixesAdvertised+
" +
	"prefixes_received (RprefixesReceived
" +
	"	bfd_state (	RbfdState%
" +
	"uptime_seconds (RuptimeSeconds\";
" +
	"ListBGPPrefixesRequest!
" +
	"peer_address (	RpeerAddress\"V
" +
	"ListBGPPrefixesResponse;
" +
	"prefixes (2.straitgateway.bgp.v1.BGPPrefixRprefixes\"Ã
" +
	"	BGPPrefix9
" +
	"prefix (2!.straitgateway.common.v1.IPPrefixRprefix
" +
	"next_hop (	RnextHop
" +
	"
" +
	"local_pref (R	localPref
" +
	"med (Rmed
" +
	"as_path (RasPath
" +
	"origin (	Rorigin2Ý
" +
	"
" +
	"BGPServiceb
" +
	"	ListPeers).straitgateway.bgp.v1.ListBGPPeersRequest*.straitgateway.bgp.v1.ListBGPPeersResponsek
" +
	"ListPrefixes,.straitgateway.bgp.v1.ListBGPPrefixesRequest-.straitgateway.bgp.v1.ListBGPPrefixesResponseBÍ
" +
	"com.straitgateway.bgp.v1BBgpProtoPZ5github.com/msaeedb40/straitgateway/proto/bgp/v1;bgpv1¢SBXªStraitgateway.Bgp.V1ÊStraitgateway\Bgp\V1â Straitgateway\Bgp\V1\GPBMetadataêStraitgateway::Bgp::V1bproto3"

var (
	file_bgp_v1_bgp_proto_rawDescOnce sync.Once
	file_bgp_v1_bgp_proto_rawDescData []byte
)

func file_bgp_v1_bgp_proto_rawDescGZIP() []byte {
	file_bgp_v1_bgp_proto_rawDescOnce.Do(func() {
		file_bgp_v1_bgp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bgp_v1_bgp_proto_rawDesc), len(file_bgp_v1_bgp_proto_rawDesc)))
	})
	return file_bgp_v1_bgp_proto_rawDescData
}

var file_bgp_v1_bgp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bgp_v1_bgp_proto_goTypes = []any{
	(*ListBGPPeersRequest)(nil),     // 0: straitgateway.bgp.v1.ListBGPPeersRequest
	(*ListBGPPeersResponse)(nil),    // 1: straitgateway.bgp.v1.ListBGPPeersResponse
	(*BGPPeerInfo)(nil),             // 2: straitgateway.bgp.v1.BGPPeerInfo
	(*ListBGPPrefixesRequest)(nil),  // 3: straitgateway.bgp.v1.ListBGPPrefixesRequest
	(*ListBGPPrefixesResponse)(nil), // 4: straitgateway.bgp.v1.ListBGPPrefixesResponse
	(*BGPPrefix)(nil),               // 5: straitgateway.bgp.v1.BGPPrefix
	(*v1.IPPrefix)(nil),             // 6: straitgateway.common.v1.IPPrefix
}
var file_bgp_v1_bgp_proto_depIdxs = []int32{
	2, // 0: straitgateway.bgp.v1.ListBGPPeersResponse.peers:type_name -> straitgateway.bgp.v1.BGPPeerInfo
	5, // 1: straitgateway.bgp.v1.ListBGPPrefixesResponse.prefixes:type_name -> straitgateway.bgp.v1.BGPPrefix
	6, // 2: straitgateway.bgp.v1.BGPPrefix.prefix:type_name -> straitgateway.common.v1.IPPrefix
	0, // 3: straitgateway.bgp.v1.BGPService.ListPeers:input_type -> straitgateway.bgp.v1.ListBGPPeersRequest
	3, // 4: straitgateway.bgp.v1.BGPService.ListPrefixes:input_type -> straitgateway.bgp.v1.ListBGPPrefixesRequest
	1, // 5: straitgateway.bgp.v1.BGPService.ListPeers:output_type -> straitgateway.bgp.v1.ListBGPPeersResponse
	4, // 6: straitgateway.bgp.v1.BGPService.ListPrefixes:output_type -> straitgateway.bgp.v1.ListBGPPrefixesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bgp_v1_bgp_proto_init() }
func file_bgp_v1_bgp_proto_init() {
	if File_bgp_v1_bgp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bgp_v1_bgp_proto_rawDesc), len(file_bgp_v1_bgp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bgp_v1_bgp_proto_goTypes,
		DependencyIndexes: file_bgp_v1_bgp_proto_depIdxs,
		MessageInfos:      file_bgp_v1_bgp_proto_msgTypes,
	}.Build()
	File_bgp_v1_bgp_proto = out.File
	file_bgp_v1_bgp_proto_goTypes = nil
	file_bgp_v1_bgp_proto_depIdxs = nil
}
