// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: bgp/v1/bgp.proto

package bgpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BGPService_ListPeers_FullMethodName    = "/straitgateway.bgp.v1.BGPService/ListPeers"
	BGPService_ListPrefixes_FullMethodName = "/straitgateway.bgp.v1.BGPService/ListPrefixes"
)

// BGPServiceClient is the client API for BGPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BGPServiceClient interface {
	ListPeers(ctx context.Context, in *ListBGPPeersRequest, opts ...grpc.CallOption) (*ListBGPPeersResponse, error)
	ListPrefixes(ctx context.Context, in *ListBGPPrefixesRequest, opts ...grpc.CallOption) (*ListBGPPrefixesResponse, error)
}

type bGPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBGPServiceClient(cc grpc.ClientConnInterface) BGPServiceClient {
	return &bGPServiceClient{cc}
}

func (c *bGPServiceClient) ListPeers(ctx context.Context, in *ListBGPPeersRequest, opts ...grpc.CallOption) (*ListBGPPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBGPPeersResponse)
	err := c.cc.Invoke(ctx, BGPService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPServiceClient) ListPrefixes(ctx context.Context, in *ListBGPPrefixesRequest, opts ...grpc.CallOption) (*ListBGPPrefixesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBGPPrefixesResponse)
	err := c.cc.Invoke(ctx, BGPService_ListPrefixes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BGPServiceServer is the server API for BGPService service.
// All implementations must embed UnimplementedBGPServiceServer
// for forward compatibility.
type BGPServiceServer interface {
	ListPeers(context.Context, *ListBGPPeersRequest) (*ListBGPPeersResponse, error)
	ListPrefixes(context.Context, *ListBGPPrefixesRequest) (*ListBGPPrefixesResponse, error)
	mustEmbedUnimplementedBGPServiceServer()
}

// UnimplementedBGPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBGPServiceServer struct{}

func (UnimplementedBGPServiceServer) ListPeers(context.Context, *ListBGPPeersRequest) (*ListBGPPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedBGPServiceServer) ListPrefixes(context.Context, *ListBGPPrefixesRequest) (*ListBGPPrefixesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrefixes not implemented")
}
func (UnimplementedBGPServiceServer) mustEmbedUnimplementedBGPServiceServer() {}
func (UnimplementedBGPServiceServer) testEmbeddedByValue()                    {}

// UnsafeBGPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BGPServiceServer will
// result in compilation errors.
type UnsafeBGPServiceServer interface {
	mustEmbedUnimplementedBGPServiceServer()
}

func RegisterBGPServiceServer(s grpc.ServiceRegistrar, srv BGPServiceServer) {
	// If the following call panics, it indicates UnimplementedBGPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BGPService_ServiceDesc, srv)
}

func _BGPService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBGPPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPServiceServer).ListPeers(ctx, req.(*ListBGPPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPService_ListPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBGPPrefixesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPServiceServer).ListPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPService_ListPrefixes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPServiceServer).ListPrefixes(ctx, req.(*ListBGPPrefixesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BGPService_ServiceDesc is the grpc.ServiceDesc for BGPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BGPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "straitgateway.bgp.v1.BGPService",
	HandlerType: (*BGPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPeers",
			Handler:    _BGPService_ListPeers_Handler,
		},
		{
			MethodName: "ListPrefixes",
			Handler:    _BGPService_ListPrefixes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bgp/v1/bgp.proto",
}
