version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "developer"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      ebpf:
        patterns:
          - "github.com/cilium/ebpf*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
