version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - misspell
    - nilerr
    - noctx
    - unconvert
    - unparam
  disable:
    - depguard
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - unparam
        path: cni/client\.go
      - linters:
          - all
        path: hack/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
