// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L4Protocol represents a Layer-4 protocol.
type L4Protocol int32

const (
	L4Protocol_L4_PROTOCOL_UNSPECIFIED L4Protocol = 0
	L4Protocol_L4_PROTOCOL_TCP         L4Protocol = 1
	L4Protocol_L4_PROTOCOL_UDP         L4Protocol = 2
	L4Protocol_L4_PROTOCOL_ICMP        L4Protocol = 3
	L4Protocol_L4_PROTOCOL_SCTP        L4Protocol = 4
)

// Enum value maps for L4Protocol.
var (
	L4Protocol_name = map[int32]string{
		0: "L4_PROTOCOL_UNSPECIFIED",
		1: "L4_PROTOCOL_TCP",
		2: "L4_PROTOCOL_UDP",
		3: "L4_PROTOCOL_ICMP",
		4: "L4_PROTOCOL_SCTP",
	}
	L4Protocol_value = map[string]int32{
		"L4_PROTOCOL_UNSPECIFIED": 0,
		"L4_PROTOCOL_TCP":         1,
		"L4_PROTOCOL_UDP":         2,
		"L4_PROTOCOL_ICMP":        3,
		"L4_PROTOCOL_SCTP":        4,
	}
)

func (x L4Protocol) Enum() *L4Protocol {
	p := new(L4Protocol)
	*p = x
	return p
}

func (x L4Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L4Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (L4Protocol) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x L4Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L4Protocol.Descriptor instead.
func (L4Protocol) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// IPAddress represents an IPv4 or IPv6 address.
type IPAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Address:
	//
	//	*IPAddress_Ipv4
	//	*IPAddress_Ipv6
	Address       isIPAddress_Address `protobuf_oneof:"address"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *IPAddress) GetAddress() isIPAddress_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *IPAddress) GetIpv4() uint32 {
	if x != nil {
		if x, ok := x.Address.(*IPAddress_Ipv4); ok {
			return x.Ipv4
		}
	}
	return 0
}

func (x *IPAddress) GetIpv6() []byte {
	if x != nil {
		if x, ok := x.Address.(*IPAddress_Ipv6); ok {
			return x.Ipv6
		}
	}
	return nil
}

type isIPAddress_Address interface {
	isIPAddress_Address()
}

type IPAddress_Ipv4 struct {
	Ipv4 uint32 `protobuf:"fixed32,1,opt,name=ipv4,proto3,oneof"`
}

type IPAddress_Ipv6 struct {
	Ipv6 []byte `protobuf:"bytes,2,opt,name=ipv6,proto3,oneof"` // 16 bytes
}

func (*IPAddress_Ipv4) isIPAddress_Address() {}

func (*IPAddress_Ipv6) isIPAddress_Address() {}

// IPPrefix represents an IP CIDR prefix.
type IPPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *IPAddress             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32                 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPrefix) Reset() {
	*x = IPPrefix{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPrefix) ProtoMessage() {}

func (x *IPPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPrefix.ProtoReflect.Descriptor instead.
func (*IPPrefix) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *IPPrefix) GetAddress() *IPAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *IPPrefix) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

// Identity is the 32-bit straitgateway security identity.
type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// labels_hash is a FNV-1a hash of the sorted label set.
	LabelsHash    uint64 `protobuf:"varint,2,opt,name=labels_hash,json=labelsHash,proto3" json:"labels_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Identity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Identity) GetLabelsHash() uint64 {
	if x != nil {
		return x.LabelsHash
	}
	return 0
}

// Endpoint represents a pod or host endpoint.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Ipv4          *IPAddress             `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          *IPAddress             `protobuf:"bytes,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Identity      *Identity              `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	SegmentId     uint32                 `protobuf:"varint,6,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Endpoint) GetIpv4() *IPAddress {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *Endpoint) GetIpv6() *IPAddress {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

func (x *Endpoint) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Endpoint) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

// L4Port represents a port range.
type L4Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	EndPort       uint32                 `protobuf:"varint,2,opt,name=end_port,json=endPort,proto3" json:"end_port,omitempty"` // 0 = single port
	Protocol      L4Protocol             `protobuf:"varint,3,opt,name=protocol,proto3,enum=straitgateway.common.v1.L4Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L4Port) Reset() {
	*x = L4Port{}
	mi := &file_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L4Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L4Port) ProtoMessage() {}

func (x *L4Port) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L4Port.ProtoReflect.Descriptor instead.
func (*L4Port) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *L4Port) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *L4Port) GetEndPort() uint32 {
	if x != nil {
		return x.EndPort
	}
	return 0
}

func (x *L4Port) GetProtocol() L4Protocol {
	if x != nil {
		return x.Protocol
	}
	return L4Protocol_L4_PROTOCOL_UNSPECIFIED
}

// ObservabilityAttributes represents the 11-attribute canonical model.
type ObservabilityAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,5,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	Identity      uint32                 `protobuf:"varint,6,opt,name=identity,proto3" json:"identity,omitempty"`
	SegmentId     uint32                 `protobuf:"varint,7,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	Protocol      string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Action        string                 `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	DropReason    string                 `protobuf:"bytes,11,opt,name=drop_reason,json=dropReason,proto3" json:"drop_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityAttributes) Reset() {
	*x = ObservabilityAttributes{}
	mi := &file_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityAttributes) ProtoMessage() {}

func (x *ObservabilityAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityAttributes.ProtoReflect.Descriptor instead.
func (*ObservabilityAttributes) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ObservabilityAttributes) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ObservabilityAttributes) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ObservabilityAttributes) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObservabilityAttributes) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ObservabilityAttributes) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *ObservabilityAttributes) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *ObservabilityAttributes) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *ObservabilityAttributes) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ObservabilityAttributes) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ObservabilityAttributes) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ObservabilityAttributes) GetDropReason() string {
	if x != nil {
		return x.DropReason
	}
	return ""
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\x17straitgateway.common.v1\"B\n" +
	"\tIPAddress\x12\x14\n" +
	"\x04ipv4\x18\x01 \x01(\aH\x00R\x04ipv4\x12\x14\n" +
	"\x04ipv6\x18\x02 \x01(\fH\x00R\x04ipv6B\t\n" +
	"\aaddress\"m\n" +
	"\bIPPrefix\x12<\n" +
	"\aaddress\x18\x01 \x01(\v2\".straitgateway.common.v1.IPAddressR\aaddress\x12#\n" +
	"\rprefix_length\x18\x02 \x01(\rR\fprefixLength\";\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vlabels_hash\x18\x02 \x01(\x04R\n" +
	"labelsHash\"\x8a\x02\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x126\n" +
	"\x04ipv4\x18\x03 \x01(\v2\".straitgateway.common.v1.IPAddressR\x04ipv4\x126\n" +
	"\x04ipv6\x18\x04 \x01(\v2\".straitgateway.common.v1.IPAddressR\x04ipv6\x12=\n" +
	"\bidentity\x18\x05 \x01(\v2!.straitgateway.common.v1.IdentityR\bidentity\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x06 \x01(\rR\tsegmentId\"x\n" +
	"\x06L4Port\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x19\n" +
	"\bend_port\x18\x02 \x01(\rR\aendPort\x12?\n" +
	"\bprotocol\x18\x03 \x01(\x0e2#.straitgateway.common.v1.L4ProtocolR\bprotocol\"\xe5\x02\n" +
	"\x17ObservabilityAttributes\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12#\n" +
	"\rworkload_name\x18\x05 \x01(\tR\fworkloadName\x12\x1a\n" +
	"\bidentity\x18\x06 \x01(\rR\bidentity\x12\x1d\n" +
	"\n" +
	"segment_id\x18\a \x01(\rR\tsegmentId\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12\x1f\n" +
	"\vdrop_reason\x18\v \x01(\tR\n" +
	"dropReason*\x7f\n" +
	"\n" +
	"L4Protocol\x12\x1b\n" +
	"\x17L4_PROTOCOL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fL4_PROTOCOL_TCP\x10\x01\x12\x13\n" +
	"\x0fL4_PROTOCOL_UDP\x10\x02\x12\x14\n" +
	"\x10L4_PROTOCOL_ICMP\x10\x03\x12\x14\n" +
	"\x10L4_PROTOCOL_SCTP\x10\x04B\xe5\x01\n" +
	"\x1bcom.straitgateway.common.v1B\vCommonProtoP\x01Z;github.com/msaeedb40/straitgateway/proto/common/v1;commonv1\xa2\x02\x03SCX\xaa\x02\x17Straitgateway.Common.V1\xca\x02\x17Straitgateway\\Common\\V1\xe2\x02#Straitgateway\\Common\\V1\\GPBMetadata\xea\x02\x19Straitgateway::Common::V1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_v1_common_proto_goTypes = []any{
	(L4Protocol)(0),                 // 0: straitgateway.common.v1.L4Protocol
	(*IPAddress)(nil),               // 1: straitgateway.common.v1.IPAddress
	(*IPPrefix)(nil),                // 2: straitgateway.common.v1.IPPrefix
	(*Identity)(nil),                // 3: straitgateway.common.v1.Identity
	(*Endpoint)(nil),                // 4: straitgateway.common.v1.Endpoint
	(*L4Port)(nil),                  // 5: straitgateway.common.v1.L4Port
	(*ObservabilityAttributes)(nil), // 6: straitgateway.common.v1.ObservabilityAttributes
}
var file_common_v1_common_proto_depIdxs = []int32{
	1, // 0: straitgateway.common.v1.IPPrefix.address:type_name -> straitgateway.common.v1.IPAddress
	1, // 1: straitgateway.common.v1.Endpoint.ipv4:type_name -> straitgateway.common.v1.IPAddress
	1, // 2: straitgateway.common.v1.Endpoint.ipv6:type_name -> straitgateway.common.v1.IPAddress
	3, // 3: straitgateway.common.v1.Endpoint.identity:type_name -> straitgateway.common.v1.Identity
	0, // 4: straitgateway.common.v1.L4Port.protocol:type_name -> straitgateway.common.v1.L4Protocol
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	file_common_v1_common_proto_msgTypes[0].OneofWrappers = []any{
		(*IPAddress_Ipv4)(nil),
		(*IPAddress_Ipv6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
