// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: dataplane/v1/dataplane.proto

package dataplanev1

import (
	v1 "github.com/msaeedb40/straitgateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBPFMapStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBPFMapStatsRequest) Reset() {
	*x = GetBPFMapStatsRequest{}
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBPFMapStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBPFMapStatsRequest) ProtoMessage() {}

func (x *GetBPFMapStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBPFMapStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBPFMapStatsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{0}
}

type GetBPFMapStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maps          map[string]*BPFMapStat `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBPFMapStatsResponse) Reset() {
	*x = GetBPFMapStatsResponse{}
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBPFMapStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBPFMapStatsResponse) ProtoMessage() {}

func (x *GetBPFMapStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBPFMapStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBPFMapStatsResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *GetBPFMapStatsResponse) GetMaps() map[string]*BPFMapStat {
	if x != nil {
		return x.Maps
	}
	return nil
}

type BPFMapStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       uint32                 `protobuf:"varint,1,opt,name=entries,proto3" json:"entries,omitempty"`
	MaxEntries    uint32                 `protobuf:"varint,2,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	KeySize       uint32                 `protobuf:"varint,3,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	ValueSize     uint32                 `protobuf:"varint,4,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BPFMapStat) Reset() {
	*x = BPFMapStat{}
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BPFMapStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BPFMapStat) ProtoMessage() {}

func (x *BPFMapStat) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BPFMapStat.ProtoReflect.Descriptor instead.
func (*BPFMapStat) Descriptor() ([]byte, []int) {
	return file_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *BPFMapStat) GetEntries() uint32 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *BPFMapStat) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *BPFMapStat) GetKeySize() uint32 {
	if x != nil {
		return x.KeySize
	}
	return 0
}

func (x *BPFMapStat) GetValueSize() uint32 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

func (x *BPFMapStat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type StreamFlowsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterAction   string                 `protobuf:"bytes,2,opt,name=filter_action,json=filterAction,proto3" json:"filter_action,omitempty"`
	FilterProtocol string                 `protobuf:"bytes,3,opt,name=filter_protocol,json=filterProtocol,proto3" json:"filter_protocol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamFlowsRequest) Reset() {
	*x = StreamFlowsRequest{}
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlowsRequest) ProtoMessage() {}

func (x *StreamFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlowsRequest.ProtoReflect.Descriptor instead.
func (*StreamFlowsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *StreamFlowsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StreamFlowsRequest) GetFilterAction() string {
	if x != nil {
		return x.FilterAction
	}
	return ""
}

func (x *StreamFlowsRequest) GetFilterProtocol() string {
	if x != nil {
		return x.FilterProtocol
	}
	return ""
}

type FlowEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	SrcIp         *v1.IPAddress               `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         *v1.IPAddress               `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                      `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                      `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SrcIdentity   uint32                      `protobuf:"varint,5,opt,name=src_identity,json=srcIdentity,proto3" json:"src_identity,omitempty"`
	DstIdentity   uint32                      `protobuf:"varint,6,opt,name=dst_identity,json=dstIdentity,proto3" json:"dst_identity,omitempty"`
	Protocol      v1.L4Protocol               `protobuf:"varint,7,opt,name=protocol,proto3,enum=straitgateway.common.v1.L4Protocol" json:"protocol,omitempty"`
	Direction     string                      `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	Action        string                      `protobuf:"bytes,9,opt,name=action,proto3" json:"action,omitempty"`
	Bytes         uint64                      `protobuf:"varint,10,opt,name=bytes,proto3" json:"bytes,omitempty"`
	TimestampNs   int64                       `protobuf:"varint,11,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	DropReason    string                      `protobuf:"bytes,12,opt,name=drop_reason,json=dropReason,proto3" json:"drop_reason,omitempty"`
	Attributes    *v1.ObservabilityAttributes `protobuf:"bytes,13,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_v1_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_dataplane_v1_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *FlowEvent) GetSrcIp() *v1.IPAddress {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *FlowEvent) GetDstIp() *v1.IPAddress {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *FlowEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowEvent) GetSrcIdentity() uint32 {
	if x != nil {
		return x.SrcIdentity
	}
	return 0
}

func (x *FlowEvent) GetDstIdentity() uint32 {
	if x != nil {
		return x.DstIdentity
	}
	return 0
}

func (x *FlowEvent) GetProtocol() v1.L4Protocol {
	if x != nil {
		return x.Protocol
	}
	return v1.L4Protocol(0)
}

func (x *FlowEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FlowEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FlowEvent) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *FlowEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *FlowEvent) GetDropReason() string {
	if x != nil {
		return x.DropReason
	}
	return ""
}

func (x *FlowEvent) GetAttributes() *v1.ObservabilityAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_dataplane_v1_dataplane_proto protoreflect.FileDescriptor

const file_dataplane_v1_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x1cdataplane/v1/dataplane.proto\x12\x1astraitgateway.dataplane.v1\x1a\x16common/v1/common.proto\"\x17\n" +
	"\x15GetBPFMapStatsRequest\"\xcb\x01\n" +
	"\x16GetBPFMapStatsResponse\x12P\n" +
	"\x04maps\x18\x01 \x03(\v2<.straitgateway.dataplane.v1.GetBPFMapStatsResponse.MapsEntryR\x04maps\x1a_\n" +
	"\tMapsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.straitgateway.dataplane.v1.BPFMapStatR\x05value:\x028\x01\"\x95\x01\n" +
	"\n" +
	"BPFMapStat\x12\x18\n" +
	"\aentries\x18\x01 \x01(\rR\aentries\x12\x1f\n" +
	"\vmax_entries\x18\x02 \x01(\rR\n" +
	"maxEntries\x12\x19\n" +
	"\bkey_size\x18\x03 \x01(\rR\akeySize\x12\x1d\n" +
	"\n" +
	"value_size\x18\x04 \x01(\rR\tvalueSize\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"x\n" +
	"\x12StreamFlowsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12#\n" +
	"\rfilter_action\x18\x02 \x01(\tR\ffilterAction\x12'\n" +
	"\x0ffilter_protocol\x18\x03 \x01(\tR\x0efilterProtocol\"\xa0\x04\n" +
	"\tFlowEvent\x129\n" +
	"\x06src_ip\x18\x01 \x01(\v2\".straitgateway.common.v1.IPAddressR\x05srcIp\x129\n" +
	"\x06dst_ip\x18\x02 \x01(\v2\".straitgateway.common.v1.IPAddressR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12!\n" +
	"\fsrc_identity\x18\x05 \x01(\rR\vsrcIdentity\x12!\n" +
	"\fdst_identity\x18\x06 \x01(\rR\vdstIdentity\x12?\n" +
	"\bprotocol\x18\a \x01(\x0e2#.straitgateway.common.v1.L4ProtocolR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x16\n" +
	"\x06action\x18\t \x01(\tR\x06action\x12\x14\n" +
	"\x05bytes\x18\n" +
	" \x01(\x04R\x05bytes\x12!\n" +
	"\ftimestamp_ns\x18\v \x01(\x03R\vtimestampNs\x12\x1f\n" +
	"\vdrop_reason\x18\f \x01(\tR\n" +
	"dropReason\x12P\n" +
	"\n" +
	"attributes\x18\r \x01(\v20.straitgateway.common.v1.ObservabilityAttributesR\n" +
	"attributes2\xf3\x01\n" +
	"\x10DataplaneService\x12w\n" +
	"\x0eGetBPFMapStats\x121.straitgateway.dataplane.v1.GetBPFMapStatsRequest\x1a2.straitgateway.dataplane.v1.GetBPFMapStatsResponse\x12f\n" +
	"\vStreamFlows\x12..straitgateway.dataplane.v1.StreamFlowsRequest\x1a%.straitgateway.dataplane.v1.FlowEvent0\x01B\xfd\x01\n" +
	"\x1ecom.straitgateway.dataplane.v1B\x0eDataplaneProtoP\x01ZAgithub.com/msaeedb40/straitgateway/proto/dataplane/v1;dataplanev1\xa2\x02\x03SDX\xaa\x02\x1aStraitgateway.Dataplane.V1\xca\x02\x1aStraitgateway\\Dataplane\\V1\xe2\x02&Straitgateway\\Dataplane\\V1\\GPBMetadata\xea\x02\x1cStraitgateway::Dataplane::V1b\x06proto3"

var (
	file_dataplane_v1_dataplane_proto_rawDescOnce sync.Once
	file_dataplane_v1_dataplane_proto_rawDescData []byte
)

func file_dataplane_v1_dataplane_proto_rawDescGZIP() []byte {
	file_dataplane_v1_dataplane_proto_rawDescOnce.Do(func() {
		file_dataplane_v1_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_v1_dataplane_proto_rawDesc), len(file_dataplane_v1_dataplane_proto_rawDesc)))
	})
	return file_dataplane_v1_dataplane_proto_rawDescData
}

var file_dataplane_v1_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dataplane_v1_dataplane_proto_goTypes = []any{
	(*GetBPFMapStatsRequest)(nil),      // 0: straitgateway.dataplane.v1.GetBPFMapStatsRequest
	(*GetBPFMapStatsResponse)(nil),     // 1: straitgateway.dataplane.v1.GetBPFMapStatsResponse
	(*BPFMapStat)(nil),                 // 2: straitgateway.dataplane.v1.BPFMapStat
	(*StreamFlowsRequest)(nil),         // 3: straitgateway.dataplane.v1.StreamFlowsRequest
	(*FlowEvent)(nil),                  // 4: straitgateway.dataplane.v1.FlowEvent
	nil,                                // 5: straitgateway.dataplane.v1.GetBPFMapStatsResponse.MapsEntry
	(*v1.IPAddress)(nil),               // 6: straitgateway.common.v1.IPAddress
	(v1.L4Protocol)(0),                 // 7: straitgateway.common.v1.L4Protocol
	(*v1.ObservabilityAttributes)(nil), // 8: straitgateway.common.v1.ObservabilityAttributes
}
var file_dataplane_v1_dataplane_proto_depIdxs = []int32{
	5, // 0: straitgateway.dataplane.v1.GetBPFMapStatsResponse.maps:type_name -> straitgateway.dataplane.v1.GetBPFMapStatsResponse.MapsEntry
	6, // 1: straitgateway.dataplane.v1.FlowEvent.src_ip:type_name -> straitgateway.common.v1.IPAddress
	6, // 2: straitgateway.dataplane.v1.FlowEvent.dst_ip:type_name -> straitgateway.common.v1.IPAddress
	7, // 3: straitgateway.dataplane.v1.FlowEvent.protocol:type_name -> straitgateway.common.v1.L4Protocol
	8, // 4: straitgateway.dataplane.v1.FlowEvent.attributes:type_name -> straitgateway.common.v1.ObservabilityAttributes
	2, // 5: straitgateway.dataplane.v1.GetBPFMapStatsResponse.MapsEntry.value:type_name -> straitgateway.dataplane.v1.BPFMapStat
	0, // 6: straitgateway.dataplane.v1.DataplaneService.GetBPFMapStats:input_type -> straitgateway.dataplane.v1.GetBPFMapStatsRequest
	3, // 7: straitgateway.dataplane.v1.DataplaneService.StreamFlows:input_type -> straitgateway.dataplane.v1.StreamFlowsRequest
	1, // 8: straitgateway.dataplane.v1.DataplaneService.GetBPFMapStats:output_type -> straitgateway.dataplane.v1.GetBPFMapStatsResponse
	4, // 9: straitgateway.dataplane.v1.DataplaneService.StreamFlows:output_type -> straitgateway.dataplane.v1.FlowEvent
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_dataplane_v1_dataplane_proto_init() }
func file_dataplane_v1_dataplane_proto_init() {
	if File_dataplane_v1_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_v1_dataplane_proto_rawDesc), len(file_dataplane_v1_dataplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_v1_dataplane_proto_goTypes,
		DependencyIndexes: file_dataplane_v1_dataplane_proto_depIdxs,
		MessageInfos:      file_dataplane_v1_dataplane_proto_msgTypes,
	}.Build()
	File_dataplane_v1_dataplane_proto = out.File
	file_dataplane_v1_dataplane_proto_goTypes = nil
	file_dataplane_v1_dataplane_proto_depIdxs = nil
}
