{{/*
Copyright 2026 straitgateway Authors
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "straitgateway.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitgateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "straitgateway.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "straitgateway.controller.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "straitgateway.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sg-controller
          image: {{ include "straitgateway.controller.image" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - --metrics-bind-address=:9090
            - --health-probe-bind-address=:8081
            - --leader-elect={{ .Values.controller.leaderElection }}
            - --leader-election-id={{ .Values.controller.leaderElectionID }}
            - --log-level=info
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.global.clusterName | quote }}
            - name: CLUSTER_ID
              value: {{ .Values.global.clusterID | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
