{{/*
Copyright 2026 straitgateway Authors
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "straitgateway.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitgateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  gatewayClassName: {{ .Values.gatewayAPI.gatewayClass }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "straitgateway.fullname" . }}-tls
{{- end }}
