// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: transit/v1/transit.proto

package transitv1

import (
	v1 "github.com/msaeedb40/straitgateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_transit_v1_transit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{0}
}

type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentInfo         `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_transit_v1_transit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{1}
}

func (x *ListSegmentsResponse) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type SegmentInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SegmentId        uint32                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topology         string                 `protobuf:"bytes,3,opt,name=topology,proto3" json:"topology,omitempty"`
	Encryption       string                 `protobuf:"bytes,4,opt,name=encryption,proto3" json:"encryption,omitempty"`
	AttachedClusters []string               `protobuf:"bytes,5,rep,name=attached_clusters,json=attachedClusters,proto3" json:"attached_clusters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_transit_v1_transit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentInfo) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SegmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentInfo) GetTopology() string {
	if x != nil {
		return x.Topology
	}
	return ""
}

func (x *SegmentInfo) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *SegmentInfo) GetAttachedClusters() []string {
	if x != nil {
		return x.AttachedClusters
	}
	return nil
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint32                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_transit_v1_transit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{3}
}

func (x *ListPeersRequest) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_transit_v1_transit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{4}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint32                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TunnelIp      *v1.IPAddress          `protobuf:"bytes,2,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TxBytes       int64                  `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       int64                  `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	LastHandshake string                 `protobuf:"bytes,7,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_transit_v1_transit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transit_v1_transit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_transit_v1_transit_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetClusterId() uint32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *PeerInfo) GetTunnelIp() *v1.IPAddress {
	if x != nil {
		return x.TunnelIp
	}
	return nil
}

func (x *PeerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PeerInfo) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PeerInfo) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PeerInfo) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerInfo) GetLastHandshake() string {
	if x != nil {
		return x.LastHandshake
	}
	return ""
}

var File_transit_v1_transit_proto protoreflect.FileDescriptor

const file_transit_v1_transit_proto_rawDesc = "" +
	"
" +
	"transit/v1/transit.protostraitgateway.transit.v1common/v1/common.proto\"
" +
	"ListSegmentsRequest\"Y
" +
	"ListSegmentsResponseA
" +
	"segments (2%.straitgateway.transit.v1.SegmentInfoRsegments\"©
" +
	"SegmentInfo
" +
	"
" +
	"segment_id (R	segmentId
" +
	"name (	Rname
" +
	"topology (	Rtopology
" +
	"
" +
	"encryption (	R
" +
	"encryption+
" +
	"attached_clusters (	RattachedClusters\"1
" +
	"ListPeersRequest
" +
	"
" +
	"segment_id (R	segmentId\"M
" +
	"ListPeersResponse8
" +
	"peers (2\".straitgateway.transit.v1.PeerInfoRpeers\"ü
" +
	"PeerInfo
" +
	"
" +
	"cluster_id (R	clusterId?
" +
	"	tunnel_ip (2\".straitgateway.common.v1.IPAddressRtunnelIp
" +
	"state (	Rstate
" +
	"tx_bytes (RtxBytes
" +
	"rx_bytes (RrxBytes
" +
	"
" +
	"latency_ms (R	latencyMs%
" +
	"last_handshake (	RlastHandshake2å
" +
	"TransitServicem
" +
	"ListSegments-.straitgateway.transit.v1.ListSegmentsRequest..straitgateway.transit.v1.ListSegmentsResponsed
" +
	"	ListPeers*.straitgateway.transit.v1.ListPeersRequest+.straitgateway.transit.v1.ListPeersResponseBí
" +
	"com.straitgateway.transit.v1BTransitProtoPZ=github.com/msaeedb40/straitgateway/proto/transit/v1;transitv1¢STXªStraitgateway.Transit.V1ÊStraitgateway\Transit\V1â$Straitgateway\Transit\V1\GPBMetadataêStraitgateway::Transit::V1bproto3"

var (
	file_transit_v1_transit_proto_rawDescOnce sync.Once
	file_transit_v1_transit_proto_rawDescData []byte
)

func file_transit_v1_transit_proto_rawDescGZIP() []byte {
	file_transit_v1_transit_proto_rawDescOnce.Do(func() {
		file_transit_v1_transit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transit_v1_transit_proto_rawDesc), len(file_transit_v1_transit_proto_rawDesc)))
	})
	return file_transit_v1_transit_proto_rawDescData
}

var file_transit_v1_transit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transit_v1_transit_proto_goTypes = []any{
	(*ListSegmentsRequest)(nil),  // 0: straitgateway.transit.v1.ListSegmentsRequest
	(*ListSegmentsResponse)(nil), // 1: straitgateway.transit.v1.ListSegmentsResponse
	(*SegmentInfo)(nil),          // 2: straitgateway.transit.v1.SegmentInfo
	(*ListPeersRequest)(nil),     // 3: straitgateway.transit.v1.ListPeersRequest
	(*ListPeersResponse)(nil),    // 4: straitgateway.transit.v1.ListPeersResponse
	(*PeerInfo)(nil),             // 5: straitgateway.transit.v1.PeerInfo
	(*v1.IPAddress)(nil),         // 6: straitgateway.common.v1.IPAddress
}
var file_transit_v1_transit_proto_depIdxs = []int32{
	2, // 0: straitgateway.transit.v1.ListSegmentsResponse.segments:type_name -> straitgateway.transit.v1.SegmentInfo
	5, // 1: straitgateway.transit.v1.ListPeersResponse.peers:type_name -> straitgateway.transit.v1.PeerInfo
	6, // 2: straitgateway.transit.v1.PeerInfo.tunnel_ip:type_name -> straitgateway.common.v1.IPAddress
	0, // 3: straitgateway.transit.v1.TransitService.ListSegments:input_type -> straitgateway.transit.v1.ListSegmentsRequest
	3, // 4: straitgateway.transit.v1.TransitService.ListPeers:input_type -> straitgateway.transit.v1.ListPeersRequest
	1, // 5: straitgateway.transit.v1.TransitService.ListSegments:output_type -> straitgateway.transit.v1.ListSegmentsResponse
	4, // 6: straitgateway.transit.v1.TransitService.ListPeers:output_type -> straitgateway.transit.v1.ListPeersResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transit_v1_transit_proto_init() }
func file_transit_v1_transit_proto_init() {
	if File_transit_v1_transit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transit_v1_transit_proto_rawDesc), len(file_transit_v1_transit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transit_v1_transit_proto_goTypes,
		DependencyIndexes: file_transit_v1_transit_proto_depIdxs,
		MessageInfos:      file_transit_v1_transit_proto_msgTypes,
	}.Build()
	File_transit_v1_transit_proto = out.File
	file_transit_v1_transit_proto_goTypes = nil
	file_transit_v1_transit_proto_depIdxs = nil
}
