// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: dataplane/v1/dataplane.proto

package dataplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneService_GetBPFMapStats_FullMethodName = "/straitgateway.dataplane.v1.DataplaneService/GetBPFMapStats"
	DataplaneService_StreamFlows_FullMethodName    = "/straitgateway.dataplane.v1.DataplaneService/StreamFlows"
)

// DataplaneServiceClient is the client API for DataplaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataplaneServiceClient interface {
	GetBPFMapStats(ctx context.Context, in *GetBPFMapStatsRequest, opts ...grpc.CallOption) (*GetBPFMapStatsResponse, error)
	StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
}

type dataplaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneServiceClient(cc grpc.ClientConnInterface) DataplaneServiceClient {
	return &dataplaneServiceClient{cc}
}

func (c *dataplaneServiceClient) GetBPFMapStats(ctx context.Context, in *GetBPFMapStatsRequest, opts ...grpc.CallOption) (*GetBPFMapStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBPFMapStatsResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetBPFMapStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneService_ServiceDesc.Streams[0], DataplaneService_StreamFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_StreamFlowsClient = grpc.ServerStreamingClient[FlowEvent]

// DataplaneServiceServer is the server API for DataplaneService service.
// All implementations must embed UnimplementedDataplaneServiceServer
// for forward compatibility.
type DataplaneServiceServer interface {
	GetBPFMapStats(context.Context, *GetBPFMapStatsRequest) (*GetBPFMapStatsResponse, error)
	StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	mustEmbedUnimplementedDataplaneServiceServer()
}

// UnimplementedDataplaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneServiceServer struct{}

func (UnimplementedDataplaneServiceServer) GetBPFMapStats(context.Context, *GetBPFMapStatsRequest) (*GetBPFMapStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBPFMapStats not implemented")
}
func (UnimplementedDataplaneServiceServer) StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamFlows not implemented")
}
func (UnimplementedDataplaneServiceServer) mustEmbedUnimplementedDataplaneServiceServer() {}
func (UnimplementedDataplaneServiceServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneServiceServer will
// result in compilation errors.
type UnsafeDataplaneServiceServer interface {
	mustEmbedUnimplementedDataplaneServiceServer()
}

func RegisterDataplaneServiceServer(s grpc.ServiceRegistrar, srv DataplaneServiceServer) {
	// If the following call panics, it indicates UnimplementedDataplaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneService_ServiceDesc, srv)
}

func _DataplaneService_GetBPFMapStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBPFMapStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetBPFMapStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetBPFMapStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetBPFMapStats(ctx, req.(*GetBPFMapStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_StreamFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneServiceServer).StreamFlows(m, &grpc.GenericServerStream[StreamFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneService_StreamFlowsServer = grpc.ServerStreamingServer[FlowEvent]

// DataplaneService_ServiceDesc is the grpc.ServiceDesc for DataplaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "straitgateway.dataplane.v1.DataplaneService",
	HandlerType: (*DataplaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBPFMapStats",
			Handler:    _DataplaneService_GetBPFMapStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlows",
			Handler:       _DataplaneService_StreamFlows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dataplane/v1/dataplane.proto",
}
