apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: straitgatewayconfigs.straitgateway.io
spec:
  group: straitgateway.io
  names:
    kind: StraitGatewayConfig
    listKind: StraitGatewayConfigList
    plural: straitgatewayconfigs
    singular: straitgatewayconfig
    shortNames: ["sgc"]
  scope: Namespaced
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: straitgatewaynodes.straitgateway.io
spec:
  group: straitgateway.io
  names:
    kind: StraitGatewayNode
    listKind: StraitGatewayNodeList
    plural: straitgatewaynodes
    singular: straitgatewaynode
    shortNames: ["sgn"]
  scope: Cluster
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: straitgatewaypolicies.straitgateway.io
spec:
  group: straitgateway.io
  names:
    kind: StraitGatewayPolicy
    listKind: StraitGatewayPolicyList
    plural: straitgatewaypolicies
    singular: straitgatewaypolicy
    shortNames: ["sgp"]
  scope: Namespaced
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: transitgateways.straitgateway.io
spec:
  group: straitgateway.io
  names:
    kind: TransitGateway
    listKind: TransitGatewayList
    plural: transitgateways
    singular: transitgateway
    shortNames: ["tgw"]
  scope: Namespaced
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
