{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-controller
  labels:
    app.kubernetes.io/name: sg-controller
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sg-controller
subjects:
  - kind: ServiceAccount
    name: sg-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.straitd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: straitd
  labels:
    app.kubernetes.io/name: straitd
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: straitd
subjects:
  - kind: ServiceAccount
    name: straitd
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.tgwd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tgwd
  labels:
    app.kubernetes.io/name: tgwd
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: transit-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tgwd
subjects:
  - kind: ServiceAccount
    name: tgwd
    namespace: {{ .Release.Namespace }}
{{- end }}
