{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sg-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sg-controller
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: controller
{{- end }}
---
{{- if .Values.straitd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: straitd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: straitd
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: node-agent
{{- end }}
---
{{- if .Values.tgwd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tgwd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tgwd
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: transit-gateway
{{- end }}
