//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..."

package v1alpha4

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties of src into dst.
// dst must be non-nil.

func (in *StraitGatewayConfig) DeepCopyInto(out *StraitGatewayConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StraitGatewayConfig) DeepCopy() *StraitGatewayConfig {
	if in == nil { return nil }
	out := new(StraitGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StraitGatewayConfigSpec) DeepCopyInto(out *StraitGatewayConfigSpec) {
	*out = *in
	in.IPAM.DeepCopyInto(&out.IPAM)
}

func (in *StraitGatewayConfigSpec) DeepCopy() *StraitGatewayConfigSpec {
	if in == nil { return nil }
	out := new(StraitGatewayConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IPAMConfig) DeepCopyInto(out *IPAMConfig) {
	*out = *in
	if in.PodCIDRs != nil {
		out.PodCIDRs = make([]string, len(in.PodCIDRs))
		copy(out.PodCIDRs, in.PodCIDRs)
	}
	if in.ServiceCIDRs != nil {
		out.ServiceCIDRs = make([]string, len(in.ServiceCIDRs))
		copy(out.ServiceCIDRs, in.ServiceCIDRs)
	}
}

func (in *StraitGatewayConfigStatus) DeepCopyInto(out *StraitGatewayConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *StraitGatewayConfigList) DeepCopyInto(out *StraitGatewayConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]StraitGatewayConfig, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}

func (in *StraitGatewayConfigList) DeepCopy() *StraitGatewayConfigList {
	if in == nil { return nil }
	out := new(StraitGatewayConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StraitGatewayNode) DeepCopyInto(out *StraitGatewayNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StraitGatewayNode) DeepCopy() *StraitGatewayNode {
	if in == nil { return nil }
	out := new(StraitGatewayNode)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StraitGatewayNodeSpec) DeepCopyInto(out *StraitGatewayNodeSpec) {
	*out = *in
	if in.PodCIDRs != nil {
		out.PodCIDRs = make([]string, len(in.PodCIDRs))
		copy(out.PodCIDRs, in.PodCIDRs)
	}
}

func (in *StraitGatewayNodeStatus) DeepCopyInto(out *StraitGatewayNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *StraitGatewayNodeList) DeepCopyInto(out *StraitGatewayNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]StraitGatewayNode, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}

func (in *StraitGatewayNodeList) DeepCopy() *StraitGatewayNodeList {
	if in == nil { return nil }
	out := new(StraitGatewayNodeList)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StraitGatewayPolicy) DeepCopyInto(out *StraitGatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StraitGatewayPolicy) DeepCopy() *StraitGatewayPolicy {
	if in == nil { return nil }
	out := new(StraitGatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *StraitGatewayPolicySpec) DeepCopyInto(out *StraitGatewayPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Ingress != nil {
		out.Ingress = make([]PolicyRule, len(in.Ingress))
		copy(out.Ingress, in.Ingress)
	}
	if in.Egress != nil {
		out.Egress = make([]PolicyRule, len(in.Egress))
		copy(out.Egress, in.Egress)
	}
}

func (in *StraitGatewayPolicyStatus) DeepCopyInto(out *StraitGatewayPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *StraitGatewayPolicyList) DeepCopyInto(out *StraitGatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]StraitGatewayPolicy, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}

func (in *StraitGatewayPolicyList) DeepCopy() *StraitGatewayPolicyList {
	if in == nil { return nil }
	out := new(StraitGatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *StraitGatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *TransitGateway) DeepCopyInto(out *TransitGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TransitGateway) DeepCopy() *TransitGateway {
	if in == nil { return nil }
	out := new(TransitGateway)
	in.DeepCopyInto(out)
	return out
}

func (in *TransitGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *TransitGatewaySpec) DeepCopyInto(out *TransitGatewaySpec) {
	*out = *in
	if in.Networks != nil {
		out.Networks = make([]TransitNetwork, len(in.Networks))
		for i := range in.Networks { in.Networks[i].DeepCopyInto(&out.Networks[i]) }
	}
}

func (in *TransitNetwork) DeepCopyInto(out *TransitNetwork) {
	*out = *in
	if in.CIDRs != nil {
		out.CIDRs = make([]string, len(in.CIDRs))
		copy(out.CIDRs, in.CIDRs)
	}
}

func (in *TransitGatewayStatus) DeepCopyInto(out *TransitGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *TransitGatewayList) DeepCopyInto(out *TransitGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TransitGateway, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}

func (in *TransitGatewayList) DeepCopy() *TransitGatewayList {
	if in == nil { return nil }
	out := new(TransitGatewayList)
	in.DeepCopyInto(out)
	return out
}

func (in *TransitGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
