apiVersion: v1
entries:
  straitgateway:
  - annotations:
      artifacthub.io/category: network
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "false"
    apiVersion: v2
    appVersion: 1.0.0
    created: "2026-09-11T18:53:28.658646966Z"
    dependencies:
    - name: crds
      repository: file://charts/crds
      version: 1.0.0
    description: 'straitgateway — eBPF-native Kubernetes CNI, Service LB, NetworkPolicy,
      Gateway API v1.6.1, kube-proxy replacement, Multi-cluster Transit Gateway, and
      BGP/BFD routing. Built on NetKit/TCX/XDP with a strict IR-based compiler. '
    digest: 2e513550c9be22146e179cee9629eb850e021a9e3820126a5e15cdc7be7c7a91
    home: https://github.com/msaeedb40/straitgateway
    keywords:
    - cni
    - ebpf
    - networking
    - kubernetes
    - gateway-api
    - network-policy
    - service-mesh
    - transit-gateway
    - bgp
    - bfd
    - wireguard
    kubeVersion: '>= 1.34.0'
    maintainers:
    - name: msaeedb40
      url: https://github.com/msaeedb40
    name: straitgateway
    sources:
    - https://github.com/msaeedb40/straitgateway
    type: application
    urls:
    - https://msaeedb40.github.io/straitgateway/charts/straitgateway-1.0.0.tgz
    version: 1.0.0
generated: "2026-09-11T18:53:28.657626829Z"
