// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IPAMMode defines the IPAM allocation mode.
// +kubebuilder:validation:Enum=PerNode;Cluster
type IPAMMode string

const (
	IPAMModePerNode IPAMMode = "PerNode"
	IPAMModeCluster IPAMMode = "Cluster"
)

// OverlayMode defines the pod network overlay mode.
// +kubebuilder:validation:Enum=Native;VXLAN;Geneve;GRE
type OverlayMode string

const (
	OverlayModeNative OverlayMode = "Native"
	OverlayModeVXLAN  OverlayMode = "VXLAN"
	OverlayModeGeneve OverlayMode = "Geneve"
	OverlayModeGRE    OverlayMode = "GRE"
)

// NodeNetworkConfigSpec defines the desired network state for a specific node.
type NodeNetworkConfigSpec struct {
	// NodeName is the name of the Kubernetes node this config applies to.
	// +kubebuilder:validation:Required
	NodeName string `json:"nodeName"`

	// PodCIDRv4 is the IPv4 pod CIDR allocated to this node (discovered dynamically from node.spec.podCIDR).
	// +optional
	PodCIDRv4 string `json:"podCIDRv4,omitempty"`

	// PodCIDRv6 is the IPv6 pod CIDR allocated to this node.
	// +optional
	PodCIDRv6 string `json:"podCIDRv6,omitempty"`

	// Overlay defines the encapsulation mode for inter-node pod traffic.
	// +kubebuilder:default=Native
	Overlay OverlayMode `json:"overlay"`

	// IPAM defines the IP address management mode.
	// +kubebuilder:default=PerNode
	IPAM IPAMMode `json:"ipam"`

	// WireGuardPublicKey is the WireGuard public key for this node (auto-generated by straitgatewayd).
	// +optional
	WireGuardPublicKey string `json:"wireGuardPublicKey,omitempty"`

	// MTU is the MTU configured on the node. 0 means auto-detect.
	// +optional
	// +kubebuilder:validation:Minimum=576
	// +kubebuilder:validation:Maximum=9000
	MTU int32 `json:"mtu,omitempty"`
}

// DataplaneReadiness holds independent readiness conditions for each dataplane subsystem.
// Each condition is independent — CNI readiness does NOT imply service readiness.
type DataplaneReadiness struct {
	// CNIReady indicates the CNI plugin is installed and operational.
	CNIReady bool `json:"cniReady"`

	// ServiceReady indicates the service load balancer BPF maps are programmed.
	ServiceReady bool `json:"serviceReady"`

	// PolicyReady indicates the NetworkPolicy enforcement engine is active.
	PolicyReady bool `json:"policyReady"`

	// GatewayReady indicates the Gateway API dataplane is programmed.
	GatewayReady bool `json:"gatewayReady"`

	// KubeProxyReplacement indicates kube-proxy has been replaced by the eBPF service dataplane.
	KubeProxyReplacement bool `json:"kubeProxyReplacement"`

	// KubeDNSProgrammed indicates kube-dns VIP is in the eBPF service map.
	KubeDNSProgrammed bool `json:"kubeDNSProgrammed"`
}

// NodeNetworkConfigStatus defines the observed state of NodeNetworkConfig.
type NodeNetworkConfigStatus struct {
	// ObservedGeneration is the last generation reconciled.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Dataplane holds independent readiness conditions per subsystem.
	// +optional
	Dataplane DataplaneReadiness `json:"dataplane,omitempty"`

	// BPFMapRevision is the current revision of the BPF map state on this node.
	// +optional
	BPFMapRevision int64 `json:"bpfMapRevision,omitempty"`

	// Conditions holds detailed reconciliation conditions.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// NodeNetworkConfig is the per-node desired and observed network state managed by straitgatewayd.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=nnc,categories=straitgateway
// +kubebuilder:printcolumn:name="Node",type=string,JSONPath=`.spec.nodeName`
// +kubebuilder:printcolumn:name="CNI",type=boolean,JSONPath=`.status.dataplane.cniReady`
// +kubebuilder:printcolumn:name="Service",type=boolean,JSONPath=`.status.dataplane.serviceReady`
// +kubebuilder:printcolumn:name="Policy",type=boolean,JSONPath=`.status.dataplane.policyReady`
// +kubebuilder:printcolumn:name="KubeProxy",type=boolean,JSONPath=`.status.dataplane.kubeProxyReplacement`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type NodeNetworkConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NodeNetworkConfigSpec   `json:"spec,omitempty"`
	Status NodeNetworkConfigStatus `json:"status,omitempty"`
}

// NodeNetworkConfigList contains a list of NodeNetworkConfig.
// +kubebuilder:object:root=true
type NodeNetworkConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodeNetworkConfig `json:"items"`
}

// ClusterNetworkConfigSpec defines the cluster-wide networking configuration.
// All CIDRs are discovered dynamically from the Kubernetes API — never hardcoded.
type ClusterNetworkConfigSpec struct {
	// ClusterName is the unique name for this cluster.
	// +kubebuilder:validation:Required
	ClusterName string `json:"clusterName"`

	// ClusterID is the unique numeric identifier for this cluster in the transit mesh.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=1
	ClusterID uint32 `json:"clusterID"`

	// PodCIDRv4 is the cluster-wide IPv4 pod CIDR (discovered from kubeadm-config or kube-controller-manager).
	// +optional
	PodCIDRv4 string `json:"podCIDRv4,omitempty"`

	// PodCIDRv6 is the cluster-wide IPv6 pod CIDR.
	// +optional
	PodCIDRv6 string `json:"podCIDRv6,omitempty"`

	// ServiceCIDRv4 is the cluster-wide IPv4 service CIDR (discovered from API server).
	// +optional
	ServiceCIDRv4 string `json:"serviceCIDRv4,omitempty"`

	// ServiceCIDRv6 is the cluster-wide IPv6 service CIDR.
	// +optional
	ServiceCIDRv6 string `json:"serviceCIDRv6,omitempty"`

	// KubeProxyReplacement enables full kube-proxy replacement via eBPF.
	// +kubebuilder:default=true
	KubeProxyReplacement bool `json:"kubeProxyReplacement"`

	// KubeProxyMode must be "none" when KubeProxyReplacement is true.
	// +kubebuilder:default=none
	KubeProxyMode string `json:"kubeProxyMode"`

	// DualStack enables IPv4/IPv6 dual-stack networking.
	// +kubebuilder:default=false
	DualStack bool `json:"dualStack"`
}

// ClusterNetworkConfigStatus defines the observed state of ClusterNetworkConfig.
type ClusterNetworkConfigStatus struct {
	// ObservedGeneration is the last generation reconciled.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// DiscoveredPodCIDRv4 is the pod CIDR discovered from the cluster.
	// +optional
	DiscoveredPodCIDRv4 string `json:"discoveredPodCIDRv4,omitempty"`

	// DiscoveredServiceCIDRv4 is the service CIDR discovered from the cluster.
	// +optional
	DiscoveredServiceCIDRv4 string `json:"discoveredServiceCIDRv4,omitempty"`

	// ReadyNodes is the number of nodes with straitgatewayd in Ready state.
	// +optional
	ReadyNodes int32 `json:"readyNodes,omitempty"`

	// TotalNodes is the total number of schedulable nodes.
	// +optional
	TotalNodes int32 `json:"totalNodes,omitempty"`

	// Conditions holds reconciliation conditions.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// ClusterNetworkConfig is the cluster-wide straitgateway configuration.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=cnc,categories=straitgateway
// +kubebuilder:printcolumn:name="Cluster",type=string,JSONPath=`.spec.clusterName`
// +kubebuilder:printcolumn:name="PodCIDR",type=string,JSONPath=`.status.discoveredPodCIDRv4`
// +kubebuilder:printcolumn:name="ServiceCIDR",type=string,JSONPath=`.status.discoveredServiceCIDRv4`
// +kubebuilder:printcolumn:name="ReadyNodes",type=integer,JSONPath=`.status.readyNodes`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type ClusterNetworkConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClusterNetworkConfigSpec   `json:"spec,omitempty"`
	Status ClusterNetworkConfigStatus `json:"status,omitempty"`
}

// ClusterNetworkConfigList contains a list of ClusterNetworkConfig.
// +kubebuilder:object:root=true
type ClusterNetworkConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterNetworkConfig `json:"items"`
}
