// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	v1 "github.com/msaeedb40/straitgateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IfName        string                 `protobuf:"bytes,4,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	Netns         string                 `protobuf:"bytes,5,opt,name=netns,proto3" json:"netns,omitempty"`
	Ipv4          bool                   `protobuf:"varint,6,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          bool                   `protobuf:"varint,7,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPRequest) Reset() {
	*x = AllocateIPRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPRequest) ProtoMessage() {}

func (x *AllocateIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPRequest.ProtoReflect.Descriptor instead.
func (*AllocateIPRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AllocateIPRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AllocateIPRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AllocateIPRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *AllocateIPRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *AllocateIPRequest) GetIpv4() bool {
	if x != nil {
		return x.Ipv4
	}
	return false
}

func (x *AllocateIPRequest) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

type AllocateIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4Address   *v1.IPAddress          `protobuf:"bytes,1,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address   *v1.IPAddress          `protobuf:"bytes,2,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	Gateway       *v1.IPAddress          `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Ipv4Cidr      *v1.IPPrefix           `protobuf:"bytes,4,opt,name=ipv4_cidr,json=ipv4Cidr,proto3" json:"ipv4_cidr,omitempty"`
	Mtu           uint32                 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	HostIfindex   int32                  `protobuf:"varint,6,opt,name=host_ifindex,json=hostIfindex,proto3" json:"host_ifindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateIPResponse) Reset() {
	*x = AllocateIPResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIPResponse) ProtoMessage() {}

func (x *AllocateIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateIPResponse.ProtoReflect.Descriptor instead.
func (*AllocateIPResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateIPResponse) GetIpv4Address() *v1.IPAddress {
	if x != nil {
		return x.Ipv4Address
	}
	return nil
}

func (x *AllocateIPResponse) GetIpv6Address() *v1.IPAddress {
	if x != nil {
		return x.Ipv6Address
	}
	return nil
}

func (x *AllocateIPResponse) GetGateway() *v1.IPAddress {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *AllocateIPResponse) GetIpv4Cidr() *v1.IPPrefix {
	if x != nil {
		return x.Ipv4Cidr
	}
	return nil
}

func (x *AllocateIPResponse) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *AllocateIPResponse) GetHostIfindex() int32 {
	if x != nil {
		return x.HostIfindex
	}
	return 0
}

type ReleaseIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Ipv4Address   *v1.IPAddress          `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseIPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ReleaseIPRequest) GetIpv4Address() *v1.IPAddress {
	if x != nil {
		return x.Ipv4Address
	}
	return nil
}

type ReleaseIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPResponse) Reset() {
	*x = ReleaseIPResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPResponse) ProtoMessage() {}

func (x *ReleaseIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPResponse.ProtoReflect.Descriptor instead.
func (*ReleaseIPResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ConfigureEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Ipv4Address   *v1.IPAddress          `protobuf:"bytes,4,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	HostIfindex   int32                  `protobuf:"varint,5,opt,name=host_ifindex,json=hostIfindex,proto3" json:"host_ifindex,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureEndpointRequest) Reset() {
	*x = ConfigureEndpointRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureEndpointRequest) ProtoMessage() {}

func (x *ConfigureEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureEndpointRequest.ProtoReflect.Descriptor instead.
func (*ConfigureEndpointRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureEndpointRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ConfigureEndpointRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ConfigureEndpointRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigureEndpointRequest) GetIpv4Address() *v1.IPAddress {
	if x != nil {
		return x.Ipv4Address
	}
	return nil
}

func (x *ConfigureEndpointRequest) GetHostIfindex() int32 {
	if x != nil {
		return x.HostIfindex
	}
	return 0
}

func (x *ConfigureEndpointRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ConfigureEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *v1.Identity           `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureEndpointResponse) Reset() {
	*x = ConfigureEndpointResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureEndpointResponse) ProtoMessage() {}

func (x *ConfigureEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureEndpointResponse.ProtoReflect.Descriptor instead.
func (*ConfigureEndpointResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureEndpointResponse) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type DeleteEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointRequest) Reset() {
	*x = DeleteEndpointRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointRequest) ProtoMessage() {}

func (x *DeleteEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEndpointRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEndpointRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type DeleteEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointResponse) Reset() {
	*x = DeleteEndpointResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointResponse) ProtoMessage() {}

func (x *DeleteEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointResponse.ProtoReflect.Descriptor instead.
func (*DeleteEndpointResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CniReady          bool                   `protobuf:"varint,1,opt,name=cni_ready,json=cniReady,proto3" json:"cni_ready,omitempty"`
	ServiceReady      bool                   `protobuf:"varint,2,opt,name=service_ready,json=serviceReady,proto3" json:"service_ready,omitempty"`
	PolicyReady       bool                   `protobuf:"varint,3,opt,name=policy_ready,json=policyReady,proto3" json:"policy_ready,omitempty"`
	GatewayReady      bool                   `protobuf:"varint,4,opt,name=gateway_ready,json=gatewayReady,proto3" json:"gateway_ready,omitempty"`
	KubeProxyReplaced bool                   `protobuf:"varint,5,opt,name=kube_proxy_replaced,json=kubeProxyReplaced,proto3" json:"kube_proxy_replaced,omitempty"`
	BpfMapRevision    int64                  `protobuf:"varint,6,opt,name=bpf_map_revision,json=bpfMapRevision,proto3" json:"bpf_map_revision,omitempty"`
	KernelVersion     string                 `protobuf:"bytes,7,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	NodeName          string                 `protobuf:"bytes,8,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version           string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatusResponse) GetCniReady() bool {
	if x != nil {
		return x.CniReady
	}
	return false
}

func (x *GetStatusResponse) GetServiceReady() bool {
	if x != nil {
		return x.ServiceReady
	}
	return false
}

func (x *GetStatusResponse) GetPolicyReady() bool {
	if x != nil {
		return x.PolicyReady
	}
	return false
}

func (x *GetStatusResponse) GetGatewayReady() bool {
	if x != nil {
		return x.GatewayReady
	}
	return false
}

func (x *GetStatusResponse) GetKubeProxyReplaced() bool {
	if x != nil {
		return x.KubeProxyReplaced
	}
	return false
}

func (x *GetStatusResponse) GetBpfMapRevision() int64 {
	if x != nil {
		return x.BpfMapRevision
	}
	return 0
}

func (x *GetStatusResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *GetStatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x16straitgateway.agent.v1\x1a\x16common/v1/common.proto\"\xc6\x01\n" +
	"\x11AllocateIPRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x17\n" +
	"\aif_name\x18\x04 \x01(\tR\x06ifName\x12\x14\n" +
	"\x05netns\x18\x05 \x01(\tR\x05netns\x12\x12\n" +
	"\x04ipv4\x18\x06 \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\a \x01(\bR\x04ipv6\"\xd5\x02\n" +
	"\x12AllocateIPResponse\x12E\n" +
	"\fipv4_address\x18\x01 \x01(\v2\".straitgateway.common.v1.IPAddressR\vipv4Address\x12E\n" +
	"\fipv6_address\x18\x02 \x01(\v2\".straitgateway.common.v1.IPAddressR\vipv6Address\x12<\n" +
	"\agateway\x18\x03 \x01(\v2\".straitgateway.common.v1.IPAddressR\agateway\x12>\n" +
	"\tipv4_cidr\x18\x04 \x01(\v2!.straitgateway.common.v1.IPPrefixR\bipv4Cidr\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\rR\x03mtu\x12!\n" +
	"\fhost_ifindex\x18\x06 \x01(\x05R\vhostIfindex\"|\n" +
	"\x10ReleaseIPRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12E\n" +
	"\fipv4_address\x18\x02 \x01(\v2\".straitgateway.common.v1.IPAddressR\vipv4Address\"\x13\n" +
	"\x11ReleaseIPResponse\"\xf1\x02\n" +
	"\x18ConfigureEndpointRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12E\n" +
	"\fipv4_address\x18\x04 \x01(\v2\".straitgateway.common.v1.IPAddressR\vipv4Address\x12!\n" +
	"\fhost_ifindex\x18\x05 \x01(\x05R\vhostIfindex\x12T\n" +
	"\x06labels\x18\x06 \x03(\v2<.straitgateway.agent.v1.ConfigureEndpointRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x19ConfigureEndpointResponse\x12=\n" +
	"\bidentity\x18\x01 \x01(\v2!.straitgateway.common.v1.IdentityR\bidentity\":\n" +
	"\x15DeleteEndpointRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\x18\n" +
	"\x16DeleteEndpointResponse\"\x12\n" +
	"\x10GetStatusRequest\"\xd5\x02\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\tcni_ready\x18\x01 \x01(\bR\bcniReady\x12#\n" +
	"\rservice_ready\x18\x02 \x01(\bR\fserviceReady\x12!\n" +
	"\fpolicy_ready\x18\x03 \x01(\bR\vpolicyReady\x12#\n" +
	"\rgateway_ready\x18\x04 \x01(\bR\fgatewayReady\x12.\n" +
	"\x13kube_proxy_replaced\x18\x05 \x01(\bR\x11kubeProxyReplaced\x12(\n" +
	"\x10bpf_map_revision\x18\x06 \x01(\x03R\x0ebpfMapRevision\x12%\n" +
	"\x0ekernel_version\x18\a \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\tnode_name\x18\b \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion2\xa2\x04\n" +
	"\fAgentService\x12c\n" +
	"\n" +
	"AllocateIP\x12).straitgateway.agent.v1.AllocateIPRequest\x1a*.straitgateway.agent.v1.AllocateIPResponse\x12`\n" +
	"\tReleaseIP\x12(.straitgateway.agent.v1.ReleaseIPRequest\x1a).straitgateway.agent.v1.ReleaseIPResponse\x12x\n" +
	"\x11ConfigureEndpoint\x120.straitgateway.agent.v1.ConfigureEndpointRequest\x1a1.straitgateway.agent.v1.ConfigureEndpointResponse\x12o\n" +
	"\x0eDeleteEndpoint\x12-.straitgateway.agent.v1.DeleteEndpointRequest\x1a..straitgateway.agent.v1.DeleteEndpointResponse\x12`\n" +
	"\tGetStatus\x12(.straitgateway.agent.v1.GetStatusRequest\x1a).straitgateway.agent.v1.GetStatusResponseB\xdd\x01\n" +
	"\x1acom.straitgateway.agent.v1B\n" +
	"AgentProtoP\x01Z9github.com/msaeedb40/straitgateway/proto/agent/v1;agentv1\xa2\x02\x03SAX\xaa\x02\x16Straitgateway.Agent.V1\xca\x02\x16Straitgateway\\Agent\\V1\xe2\x02\"Straitgateway\\Agent\\V1\\GPBMetadata\xea\x02\x18Straitgateway::Agent::V1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_v1_agent_proto_goTypes = []any{
	(*AllocateIPRequest)(nil),         // 0: straitgateway.agent.v1.AllocateIPRequest
	(*AllocateIPResponse)(nil),        // 1: straitgateway.agent.v1.AllocateIPResponse
	(*ReleaseIPRequest)(nil),          // 2: straitgateway.agent.v1.ReleaseIPRequest
	(*ReleaseIPResponse)(nil),         // 3: straitgateway.agent.v1.ReleaseIPResponse
	(*ConfigureEndpointRequest)(nil),  // 4: straitgateway.agent.v1.ConfigureEndpointRequest
	(*ConfigureEndpointResponse)(nil), // 5: straitgateway.agent.v1.ConfigureEndpointResponse
	(*DeleteEndpointRequest)(nil),     // 6: straitgateway.agent.v1.DeleteEndpointRequest
	(*DeleteEndpointResponse)(nil),    // 7: straitgateway.agent.v1.DeleteEndpointResponse
	(*GetStatusRequest)(nil),          // 8: straitgateway.agent.v1.GetStatusRequest
	(*GetStatusResponse)(nil),         // 9: straitgateway.agent.v1.GetStatusResponse
	nil,                               // 10: straitgateway.agent.v1.ConfigureEndpointRequest.LabelsEntry
	(*v1.IPAddress)(nil),              // 11: straitgateway.common.v1.IPAddress
	(*v1.IPPrefix)(nil),               // 12: straitgateway.common.v1.IPPrefix
	(*v1.Identity)(nil),               // 13: straitgateway.common.v1.Identity
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	11, // 0: straitgateway.agent.v1.AllocateIPResponse.ipv4_address:type_name -> straitgateway.common.v1.IPAddress
	11, // 1: straitgateway.agent.v1.AllocateIPResponse.ipv6_address:type_name -> straitgateway.common.v1.IPAddress
	11, // 2: straitgateway.agent.v1.AllocateIPResponse.gateway:type_name -> straitgateway.common.v1.IPAddress
	12, // 3: straitgateway.agent.v1.AllocateIPResponse.ipv4_cidr:type_name -> straitgateway.common.v1.IPPrefix
	11, // 4: straitgateway.agent.v1.ReleaseIPRequest.ipv4_address:type_name -> straitgateway.common.v1.IPAddress
	11, // 5: straitgateway.agent.v1.ConfigureEndpointRequest.ipv4_address:type_name -> straitgateway.common.v1.IPAddress
	10, // 6: straitgateway.agent.v1.ConfigureEndpointRequest.labels:type_name -> straitgateway.agent.v1.ConfigureEndpointRequest.LabelsEntry
	13, // 7: straitgateway.agent.v1.ConfigureEndpointResponse.identity:type_name -> straitgateway.common.v1.Identity
	0,  // 8: straitgateway.agent.v1.AgentService.AllocateIP:input_type -> straitgateway.agent.v1.AllocateIPRequest
	2,  // 9: straitgateway.agent.v1.AgentService.ReleaseIP:input_type -> straitgateway.agent.v1.ReleaseIPRequest
	4,  // 10: straitgateway.agent.v1.AgentService.ConfigureEndpoint:input_type -> straitgateway.agent.v1.ConfigureEndpointRequest
	6,  // 11: straitgateway.agent.v1.AgentService.DeleteEndpoint:input_type -> straitgateway.agent.v1.DeleteEndpointRequest
	8,  // 12: straitgateway.agent.v1.AgentService.GetStatus:input_type -> straitgateway.agent.v1.GetStatusRequest
	1,  // 13: straitgateway.agent.v1.AgentService.AllocateIP:output_type -> straitgateway.agent.v1.AllocateIPResponse
	3,  // 14: straitgateway.agent.v1.AgentService.ReleaseIP:output_type -> straitgateway.agent.v1.ReleaseIPResponse
	5,  // 15: straitgateway.agent.v1.AgentService.ConfigureEndpoint:output_type -> straitgateway.agent.v1.ConfigureEndpointResponse
	7,  // 16: straitgateway.agent.v1.AgentService.DeleteEndpoint:output_type -> straitgateway.agent.v1.DeleteEndpointResponse
	9,  // 17: straitgateway.agent.v1.AgentService.GetStatus:output_type -> straitgateway.agent.v1.GetStatusResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
