apiVersion: v1
kind: ConfigMap
metadata:
  name: straitgateway-cni-conflist
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: straitgateway-cni-conflist
    app.kubernetes.io/part-of: straitgateway
data:
  10-straitgateway.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "straitgateway",
      "plugins": [
        {
          "type": "strait-cni",
          "datapathMode": "{{ .Values.datapath.mode | default "netkit" }}",
          "mtu": {{ .Values.cni.mtu | default 1500 }},
          "ipam": {
            "type": "cluster-pool"
          }
        }
      ]
    }
