apiVersion: v1
kind: Service
metadata:
  name: straitd-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: straitd-metrics
    app.kubernetes.io/part-of: straitgateway
    app.kubernetes.io/component: node-agent
spec:
  type: ClusterIP
  selector:
    app: straitd
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
