{{- if and .Values.mesh.enabled .Values.mesh.mutualTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: straitgateway-mtls-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: straitgateway-mtls-certs
    app.kubernetes.io/part-of: straitgateway
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.mesh.tlsCert | default "" | b64enc | quote }}
  tls.key: {{ .Values.mesh.tlsKey | default "" | b64enc | quote }}
{{- end }}
