// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: service/v1/service.proto

package servicev1

import (
	v1 "github.com/msaeedb40/straitgateway/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_service_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_service_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceResponse) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_service_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{2}
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_service_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ClusterIp     *v1.IPAddress          `protobuf:"bytes,3,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      v1.L4Protocol          `protobuf:"varint,6,opt,name=protocol,proto3,enum=straitgateway.common.v1.L4Protocol" json:"protocol,omitempty"`
	Algorithm     string                 `protobuf:"bytes,7,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	BackendCount  uint32                 `protobuf:"varint,8,opt,name=backend_count,json=backendCount,proto3" json:"backend_count,omitempty"`
	Backends      []*BackendInfo         `protobuf:"bytes,9,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_service_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInfo) GetClusterIp() *v1.IPAddress {
	if x != nil {
		return x.ClusterIp
	}
	return nil
}

func (x *ServiceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetProtocol() v1.L4Protocol {
	if x != nil {
		return x.Protocol
	}
	return v1.L4Protocol(0)
}

func (x *ServiceInfo) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ServiceInfo) GetBackendCount() uint32 {
	if x != nil {
		return x.BackendCount
	}
	return 0
}

func (x *ServiceInfo) GetBackends() []*BackendInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

type BackendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       *v1.IPAddress          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_service_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInfo.ProtoReflect.Descriptor instead.
func (*BackendInfo) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *BackendInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackendInfo) GetAddress() *v1.IPAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BackendInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BackendInfo) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_service_v1_service_proto protoreflect.FileDescriptor

const file_service_v1_service_proto_rawDesc = "" +
	"
" +
	"service/v1/service.protostraitgateway.service.v1common/v1/common.proto\"E
" +
	"GetServiceRequest
" +
	"	namespace (	R	namespace
" +
	"name (	Rname\"U
" +
	"GetServiceResponse?
" +
	"service (2%.straitgateway.service.v1.ServiceInfoRservice\"
" +
	"ListServicesRequest\"Y
" +
	"ListServicesResponseA
" +
	"services (2%.straitgateway.service.v1.ServiceInfoRservices\"Ò
" +
	"ServiceInfo
" +
	"name (	Rname
" +
	"	namespace (	R	namespaceA
" +
	"
" +
	"cluster_ip (2\".straitgateway.common.v1.IPAddressR	clusterIp
" +
	"type (	Rtype
" +
	"port (Rport?
" +
	"protocol (2#.straitgateway.common.v1.L4ProtocolRprotocol
" +
	"	algorithm (	R	algorithm#
" +
	"backend_count (RbackendCountA
" +
	"backends	 (2%.straitgateway.service.v1.BackendInfoRbackends\"ù
" +
	"BackendInfo
" +
	"id (Rid<
" +
	"address (2\".straitgateway.common.v1.IPAddressRaddress
" +
	"port (Rport
" +
	"weight (Rweight
" +
	"state (	Rstate2Í
" +
	"ServiceLBServiceg
" +
	"
" +
	"GetService+.straitgateway.service.v1.GetServiceRequest,.straitgateway.service.v1.GetServiceResponsem
" +
	"ListServices-.straitgateway.service.v1.ListServicesRequest..straitgateway.service.v1.ListServicesResponseBÌ
" +
	"com.straitgateway.service.v1BServiceProtoPZ=github.com/msaeedb40/straitgateway/proto/service/v1;servicev1¢SSX™Straitgateway.Service.V1 Straitgateway\Service\V1‚$Straitgateway\Service\V1\GPBMetadataÍStraitgateway::Service::V1bproto3"

var (
	file_service_v1_service_proto_rawDescOnce sync.Once
	file_service_v1_service_proto_rawDescData []byte
)

func file_service_v1_service_proto_rawDescGZIP() []byte {
	file_service_v1_service_proto_rawDescOnce.Do(func() {
		file_service_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_service_proto_rawDesc), len(file_service_v1_service_proto_rawDesc)))
	})
	return file_service_v1_service_proto_rawDescData
}

var file_service_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_v1_service_proto_goTypes = []any{
	(*GetServiceRequest)(nil),    // 0: straitgateway.service.v1.GetServiceRequest
	(*GetServiceResponse)(nil),   // 1: straitgateway.service.v1.GetServiceResponse
	(*ListServicesRequest)(nil),  // 2: straitgateway.service.v1.ListServicesRequest
	(*ListServicesResponse)(nil), // 3: straitgateway.service.v1.ListServicesResponse
	(*ServiceInfo)(nil),          // 4: straitgateway.service.v1.ServiceInfo
	(*BackendInfo)(nil),          // 5: straitgateway.service.v1.BackendInfo
	(*v1.IPAddress)(nil),         // 6: straitgateway.common.v1.IPAddress
	(v1.L4Protocol)(0),           // 7: straitgateway.common.v1.L4Protocol
}
var file_service_v1_service_proto_depIdxs = []int32{
	4, // 0: straitgateway.service.v1.GetServiceResponse.service:type_name -> straitgateway.service.v1.ServiceInfo
	4, // 1: straitgateway.service.v1.ListServicesResponse.services:type_name -> straitgateway.service.v1.ServiceInfo
	6, // 2: straitgateway.service.v1.ServiceInfo.cluster_ip:type_name -> straitgateway.common.v1.IPAddress
	7, // 3: straitgateway.service.v1.ServiceInfo.protocol:type_name -> straitgateway.common.v1.L4Protocol
	5, // 4: straitgateway.service.v1.ServiceInfo.backends:type_name -> straitgateway.service.v1.BackendInfo
	6, // 5: straitgateway.service.v1.BackendInfo.address:type_name -> straitgateway.common.v1.IPAddress
	0, // 6: straitgateway.service.v1.ServiceLBService.GetService:input_type -> straitgateway.service.v1.GetServiceRequest
	2, // 7: straitgateway.service.v1.ServiceLBService.ListServices:input_type -> straitgateway.service.v1.ListServicesRequest
	1, // 8: straitgateway.service.v1.ServiceLBService.GetService:output_type -> straitgateway.service.v1.GetServiceResponse
	3, // 9: straitgateway.service.v1.ServiceLBService.ListServices:output_type -> straitgateway.service.v1.ListServicesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_v1_service_proto_init() }
func file_service_v1_service_proto_init() {
	if File_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_service_proto_rawDesc), len(file_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_service_proto_goTypes,
		DependencyIndexes: file_service_v1_service_proto_depIdxs,
		MessageInfos:      file_service_v1_service_proto_msgTypes,
	}.Build()
	File_service_v1_service_proto = out.File
	file_service_v1_service_proto_goTypes = nil
	file_service_v1_service_proto_depIdxs = nil
}
