{{- if and .Values.transit.enabled .Values.transit.wireguard.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: straitgateway-transit-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: straitgateway-transit-secret
    app.kubernetes.io/part-of: straitgateway
type: Opaque
data:
  # Base64 encoded placeholder or user provided private key
  private-key: {{ .Values.transit.wireguard.privateKey | default "" | b64enc | quote }}
{{- end }}
