// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ListPoliciesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PolicyRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ListPoliciesResponse) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIdentity   uint32                 `protobuf:"varint,1,opt,name=src_identity,json=srcIdentity,proto3" json:"src_identity,omitempty"`
	DstIdentity   uint32                 `protobuf:"varint,2,opt,name=dst_identity,json=dstIdentity,proto3" json:"dst_identity,omitempty"`
	DstPort       uint32                 `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyRule) GetSrcIdentity() uint32 {
	if x != nil {
		return x.SrcIdentity
	}
	return 0
}

func (x *PolicyRule) GetDstIdentity() uint32 {
	if x != nil {
		return x.DstIdentity
	}
	return 0
}

func (x *PolicyRule) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PolicyRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PolicyRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicyRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type EvaluatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIdentity   uint32                 `protobuf:"varint,1,opt,name=src_identity,json=srcIdentity,proto3" json:"src_identity,omitempty"`
	DstIdentity   uint32                 `protobuf:"varint,2,opt,name=dst_identity,json=dstIdentity,proto3" json:"dst_identity,omitempty"`
	DstPort       uint32                 `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePolicyRequest) Reset() {
	*x = EvaluatePolicyRequest{}
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyRequest) ProtoMessage() {}

func (x *EvaluatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyRequest.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluatePolicyRequest) GetSrcIdentity() uint32 {
	if x != nil {
		return x.SrcIdentity
	}
	return 0
}

func (x *EvaluatePolicyRequest) GetDstIdentity() uint32 {
	if x != nil {
		return x.DstIdentity
	}
	return 0
}

func (x *EvaluatePolicyRequest) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *EvaluatePolicyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type EvaluatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	PolicyName    string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePolicyResponse) Reset() {
	*x = EvaluatePolicyResponse{}
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyResponse) ProtoMessage() {}

func (x *EvaluatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyResponse.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluatePolicyResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EvaluatePolicyResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EvaluatePolicyResponse) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

var File_policy_v1_policy_proto protoreflect.FileDescriptor

const file_policy_v1_policy_proto_rawDesc = "" +
	"
" +
	"policy/v1/policy.protostraitgateway.policy.v1\"3
" +
	"ListPoliciesRequest
" +
	"	namespace (	R	namespace\"Q
" +
	"ListPoliciesResponse9
" +
	"rules (2#.straitgateway.policy.v1.PolicyRuleRrules\"Û
" +
	"
" +
	"PolicyRule!
" +
	"src_identity (RsrcIdentity!
" +
	"dst_identity (RdstIdentity
" +
	"dst_port (RdstPort
" +
	"protocol (	Rprotocol
" +
	"action (	Raction
" +
	"priority (Rpriority
" +
	"	direction (	R	direction\"”
" +
	"EvaluatePolicyRequest!
" +
	"src_identity (RsrcIdentity!
" +
	"dst_identity (RdstIdentity
" +
	"dst_port (RdstPort
" +
	"protocol (	Rprotocol\"m
" +
	"EvaluatePolicyResponse
" +
	"action (	Raction
" +
	"priority (Rpriority
" +
	"policy_name (	R
" +
	"policyName2ï
" +
	"PolicyServicek
" +
	"ListPolicies,.straitgateway.policy.v1.ListPoliciesRequest-.straitgateway.policy.v1.ListPoliciesResponseq
" +
	"EvaluatePolicy..straitgateway.policy.v1.EvaluatePolicyRequest/.straitgateway.policy.v1.EvaluatePolicyResponseBå
" +
	"com.straitgateway.policy.v1BPolicyProtoPZ;github.com/msaeedb40/straitgateway/proto/policy/v1;policyv1¢SPXªStraitgateway.Policy.V1ÊStraitgateway\Policy\V1â#Straitgateway\Policy\V1\GPBMetadataêStraitgateway::Policy::V1bproto3"

var (
	file_policy_v1_policy_proto_rawDescOnce sync.Once
	file_policy_v1_policy_proto_rawDescData []byte
)

func file_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)))
	})
	return file_policy_v1_policy_proto_rawDescData
}

var file_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_policy_v1_policy_proto_goTypes = []any{
	(*ListPoliciesRequest)(nil),    // 0: straitgateway.policy.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),   // 1: straitgateway.policy.v1.ListPoliciesResponse
	(*PolicyRule)(nil),             // 2: straitgateway.policy.v1.PolicyRule
	(*EvaluatePolicyRequest)(nil),  // 3: straitgateway.policy.v1.EvaluatePolicyRequest
	(*EvaluatePolicyResponse)(nil), // 4: straitgateway.policy.v1.EvaluatePolicyResponse
}
var file_policy_v1_policy_proto_depIdxs = []int32{
	2, // 0: straitgateway.policy.v1.ListPoliciesResponse.rules:type_name -> straitgateway.policy.v1.PolicyRule
	0, // 1: straitgateway.policy.v1.PolicyService.ListPolicies:input_type -> straitgateway.policy.v1.ListPoliciesRequest
	3, // 2: straitgateway.policy.v1.PolicyService.EvaluatePolicy:input_type -> straitgateway.policy.v1.EvaluatePolicyRequest
	1, // 3: straitgateway.policy.v1.PolicyService.ListPolicies:output_type -> straitgateway.policy.v1.ListPoliciesResponse
	4, // 4: straitgateway.policy.v1.PolicyService.EvaluatePolicy:output_type -> straitgateway.policy.v1.EvaluatePolicyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policy_v1_policy_proto_init() }
func file_policy_v1_policy_proto_init() {
	if File_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_v1_policy_proto_rawDesc), len(file_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_policy_v1_policy_proto = out.File
	file_policy_v1_policy_proto_goTypes = nil
	file_policy_v1_policy_proto_depIdxs = nil
}
