// Copyright 2026 straitgateway Authors
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysRequest) Reset() {
	*x = ListGatewaysRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysRequest) ProtoMessage() {}

func (x *ListGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type ListGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*GatewayInfo         `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysResponse) Reset() {
	*x = ListGatewaysResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysResponse) ProtoMessage() {}

func (x *ListGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ListGatewaysResponse) GetGateways() []*GatewayInfo {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type GatewayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GatewayClass  string                 `protobuf:"bytes,3,opt,name=gateway_class,json=gatewayClass,proto3" json:"gateway_class,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Listeners     []*ListenerInfo        `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty"`
	Ready         bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInfo) Reset() {
	*x = GatewayInfo{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInfo) ProtoMessage() {}

func (x *GatewayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInfo.ProtoReflect.Descriptor instead.
func (*GatewayInfo) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GatewayInfo) GetGatewayClass() string {
	if x != nil {
		return x.GatewayClass
	}
	return ""
}

func (x *GatewayInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GatewayInfo) GetListeners() []*ListenerInfo {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *GatewayInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ListenerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	RouteCount    uint32                 `protobuf:"varint,4,opt,name=route_count,json=routeCount,proto3" json:"route_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerInfo) Reset() {
	*x = ListenerInfo{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerInfo) ProtoMessage() {}

func (x *ListenerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerInfo.ProtoReflect.Descriptor instead.
func (*ListenerInfo) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListenerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenerInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListenerInfo) GetRouteCount() uint32 {
	if x != nil {
		return x.RouteCount
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoutesRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *ListRoutesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteInfo           `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ListRoutesResponse) GetRoutes() []*RouteInfo {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ParentGateway string                 `protobuf:"bytes,4,opt,name=parent_gateway,json=parentGateway,proto3" json:"parent_gateway,omitempty"`
	Hostnames     []string               `protobuf:"bytes,5,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	BackendCount  uint32                 `protobuf:"varint,6,opt,name=backend_count,json=backendCount,proto3" json:"backend_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *RouteInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RouteInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RouteInfo) GetParentGateway() string {
	if x != nil {
		return x.ParentGateway
	}
	return ""
}

func (x *RouteInfo) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

func (x *RouteInfo) GetBackendCount() uint32 {
	if x != nil {
		return x.BackendCount
	}
	return 0
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"
" +
	"gateway/v1/gateway.protostraitgateway.gateway.v1\"
" +
	"ListGatewaysRequest\"Y
" +
	"ListGatewaysResponseA
" +
	"gateways (2%.straitgateway.gateway.v1.GatewayInfoRgateways\"Þ
" +
	"GatewayInfo
" +
	"name (	Rname
" +
	"	namespace (	R	namespace#
" +
	"gateway_class (	RgatewayClass
" +
	"	addresses (	R	addressesD
" +
	"	listeners (2&.straitgateway.gateway.v1.ListenerInfoR	listeners
" +
	"ready (Rready\"s
" +
	"ListenerInfo
" +
	"name (	Rname
" +
	"protocol (	Rprotocol
" +
	"port (Rport
" +
	"route_count (R
" +
	"routeCount\"K
" +
	"ListRoutesRequest
" +
	"gateway (	Rgateway
" +
	"	namespace (	R	namespace\"Q
" +
	"ListRoutesResponse;
" +
	"routes (2#.straitgateway.gateway.v1.RouteInfoRroutes\"»
" +
	"	RouteInfo
" +
	"name (	Rname
" +
	"	namespace (	R	namespace
" +
	"type (	Rtype%
" +
	"parent_gateway (	RparentGateway
" +
	"	hostnames (	R	hostnames#
" +
	"backend_count (RbackendCount2è
" +
	"GatewayServicem
" +
	"ListGateways-.straitgateway.gateway.v1.ListGatewaysRequest..straitgateway.gateway.v1.ListGatewaysResponseg
" +
	"
" +
	"ListRoutes+.straitgateway.gateway.v1.ListRoutesRequest,.straitgateway.gateway.v1.ListRoutesResponseBí
" +
	"com.straitgateway.gateway.v1BGatewayProtoPZ=github.com/msaeedb40/straitgateway/proto/gateway/v1;gatewayv1¢SGXªStraitgateway.Gateway.V1ÊStraitgateway\Gateway\V1â$Straitgateway\Gateway\V1\GPBMetadataêStraitgateway::Gateway::V1bproto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*ListGatewaysRequest)(nil),  // 0: straitgateway.gateway.v1.ListGatewaysRequest
	(*ListGatewaysResponse)(nil), // 1: straitgateway.gateway.v1.ListGatewaysResponse
	(*GatewayInfo)(nil),          // 2: straitgateway.gateway.v1.GatewayInfo
	(*ListenerInfo)(nil),         // 3: straitgateway.gateway.v1.ListenerInfo
	(*ListRoutesRequest)(nil),    // 4: straitgateway.gateway.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),   // 5: straitgateway.gateway.v1.ListRoutesResponse
	(*RouteInfo)(nil),            // 6: straitgateway.gateway.v1.RouteInfo
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2, // 0: straitgateway.gateway.v1.ListGatewaysResponse.gateways:type_name -> straitgateway.gateway.v1.GatewayInfo
	3, // 1: straitgateway.gateway.v1.GatewayInfo.listeners:type_name -> straitgateway.gateway.v1.ListenerInfo
	6, // 2: straitgateway.gateway.v1.ListRoutesResponse.routes:type_name -> straitgateway.gateway.v1.RouteInfo
	0, // 3: straitgateway.gateway.v1.GatewayService.ListGateways:input_type -> straitgateway.gateway.v1.ListGatewaysRequest
	4, // 4: straitgateway.gateway.v1.GatewayService.ListRoutes:input_type -> straitgateway.gateway.v1.ListRoutesRequest
	1, // 5: straitgateway.gateway.v1.GatewayService.ListGateways:output_type -> straitgateway.gateway.v1.ListGatewaysResponse
	5, // 6: straitgateway.gateway.v1.GatewayService.ListRoutes:output_type -> straitgateway.gateway.v1.ListRoutesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
